name: "run api test"  

on:
  workflow_dispatch:


jobs:
  run-api-test:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout code 
        uses: actions/checkout@v4.1.1
      - name: Install Bruno
        run:  npm install -g @usebruno/cli 
      - name: Run tests
        run: | 
          cd demo-collection && \
          bru run



