name: "httpexpect api test"  

on:
  workflow_dispatch:

jobs:
  run-with-httpexpect:
    runs-on: ubunt-latest
    steps:
      - name: Checkout code and install go lang
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
      - uses: actions/setup-go@v4
      - run: go version  

      - name: run tests with httpexpect
        run: make test-api