name: "bruno api testing"  

on:
  workflow_dispatch:

jobs:
  run-with-bruno:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Install Bruno
        run: npm install -g @usebruno/cli 

      - name: Run tests
        run: bru run --env-var baseUrl="https://reqres.in/api"
